// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/TongChen15/go-camp/wk4/internal/datamodel"
)

// Injectors from wire.go:

func initializeCluster(name string) (*datamodel.Cluster, error) {
	provisionState := datamodel.NewProvisionState()
	event := datamodel.NewEvent(name)
	cluster := datamodel.NewCluster(name, provisionState, event)
	return cluster, nil
}
